apiVersion: v1
kind: ServiceAccount
metadata:
  name: patcher
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: group-sync-secret-patcher
rules:
- apiGroups: [""]
  resources: ["secrets"]
  resourceNames: ["oidc-client-secret", "ocp-oauth"]
  verbs: ["get", "list", "watch", "patch"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: group-sync-secret-patcher
subjects:
  - kind: ServiceAccount
    name: patcher
    namespace: group-sync-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: group-sync-secret-patcher
