apiVersion: v1
kind: ServiceAccount
metadata:
  name: patcher
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: secret-patcher
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    resourceNames: ["keycloak-credentials"]
    verbs: ["patch"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: secret-patcher
subjects:
  - kind: ServiceAccount
    name: patcher
    namespace: group-sync-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: secret-patcher
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: group-sync-patcher-secret-reader
subjects:
  - kind: ServiceAccount
    name: patcher
    namespace: group-sync-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: secret-reader
