apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: argocd-app-of-app
    version: 0.4.1
    repo: https://gnunn-gitops.github.io/helm-charts
    namespace: openshift-gitops
    valuesFile: values.yaml
