apiVersion: openidclient.keycloak.crossplane.io/v1alpha1
kind: Client
metadata:
  name: ocp-oauth-client
spec:
  forProvider:
    clientId: ocp-oauth
    name: "${client_ocp-oauth}"
    realmId: vagabond-studios
    rootUrl: https://oauth-openshift.apps-crc.testing/oauth2callback
    validRedirectUris:
      - /oidc-keycloak
    accessType: CONFIDENTIAL
    clientAuthenticatorType: client-secret
    clientSecretSecretRef:
      namespace: keycloak
      name: ocp-oauth
      key: clientSecret
    standardFlowEnabled: true
    directAccessGrantsEnabled: true
    implicitFlowEnabled: false
    consentRequired: false
---
apiVersion: openidclient.keycloak.crossplane.io/v1alpha1
kind: ClientDefaultScopes
metadata:
  name: ocp-oauth-client-default-scopes
spec:
  forProvider:
    clientId: ocp-oauth
    realmId: vagabond-studios
    defaultScopes:
      - profile
      - email
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ocp-oauth-client-secret
spec:
  target:
    name: ocp-oauth
    template:
      engineVersion: v2
      data:
        clientSecret: "{{ .password }}"
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Password
          name: password-generator
