apiVersion: openidclient.keycloak.crossplane.io/v1alpha1
kind: Client
metadata:
  name: ocp-oauth-client
spec:
  forProvider:
    clientId: ocp-oauth
    name: "${client_ocp-oauth}"
    realmId: vagabond-studios
    rootUrl: https://oauth-openshift.apps-crc.testing/oauth2callback
    validRedirectUris:
      - /oidc-keycloak
    accessType: CONFIDENTIAL
    clientAuthenticatorType: client-secret
    clientSecretSecretRef:
      namespace: keycloak
      name: ocp-oauth
      key: clientSecret
    standardFlowEnabled: true
    directAccessGrantsEnabled: true
    implicitFlowEnabled: false
    consentRequired: false
