apiVersion: v1
kind: ServiceAccount
metadata:
  name: patcher
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: secret-patcher
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    resourceNames: ["oidc-client-secret"]
    verbs: ["patch"]
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: openshift-config-patcher-secret-reader
rules:
- apiGroups: [""]
  resources: ["secrets"]
  resourceNames: ["oidc-client-secret", "ocp-oauth"]
  verbs: ["get", "list", "watch"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: secret-patcher
subjects:
  - kind: ServiceAccount
    name: patcher
    namespace: openshift-config
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: secret-patcher
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: openshift-config-patcher-secret-reader
subjects:
  - kind: ServiceAccount
    name: patcher
    namespace: openshift-config
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: openshift-config-patcher-secret-reader
