apiVersion: redhatcop.redhat.io/v1alpha1
kind: Patch
metadata:
  name: openshift-config-patch
  namespace: openshift-config
spec:
  serviceAccountRef:
    name: patcher
  patches:
    oidc-client-secret:
      targetObjectRef:
        apiVersion: v1
        kind: Secret
        name: oidc-client-secret
        namespace: openshift-config
      sourceObjectRefs:
        - apiVersion: v1
          kind: Secret
          name: ocp-oauth
          namespace: keycloak
      patchTemplate: |
        data:
          clientSecret: {{ (index . 1).data.clientSecret }}
      patchType: application/merge-patch+json
