apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - github.com/tim-stasse/gitops-catalog/crossplane-system/overlays/stable?ref=main

patches:
  - target:
      kind: Namespace
      name: crossplane-system
    patch: |-
      - op: add
        path: /metadata/labels/linkerd.io~1inject
        value: enabled
